# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_categoria.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Categoria(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 640)
        MainWindow.setMinimumSize(QtCore.QSize(1250, 640))
        MainWindow.setMaximumSize(QtCore.QSize(1250, 640))
        MainWindow.setStyleSheet("background-color: rgb(10, 3, 34);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 1251, 131))
        self.frame_4.setStyleSheet("background-color: black;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 70, 91, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"color: black;\n"
"border: 0.5px solid white;\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:black;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setGeometry(QtCore.QRect(1200, 70, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"background-image: url(align-justify(3).svg);\n"
"background-repeat: no-repeat;\n"
"color: white;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_34 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_34.setGeometry(QtCore.QRect(1160, 70, 31, 31))
        self.pushButton_34.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_34.setStyleSheet("background-image: url(corner-down-left(1).svg);")
        self.pushButton_34.setAutoExclusive(False)
        self.pushButton_34.setObjectName("pushButton_34")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(570, 40, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;\n"
"border-bottom: 1px solid yellow;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 120, 351, 531))
        self.frame.setStyleSheet("border: 1px solid white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(60, 20, 251, 471))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(0, 190, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 220, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 250, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 280, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 310, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 340, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(56, 92, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_2.setGeometry(QtCore.QRect(350, 120, 901, 521))
        self.stackedWidget_2.setStyleSheet("border: 1px solid white;")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.lineEdit = QtWidgets.QLineEdit(self.page_1)
        self.lineEdit.setGeometry(QtCore.QRect(60, 10, 781, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("    color: white;")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.stackedWidget_2.addWidget(self.page_1)
        self.page1_2 = QtWidgets.QWidget()
        self.page1_2.setObjectName("page1_2")
        self.scrollArea = QtWidgets.QScrollArea(self.page1_2)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 901, 521))
        self.scrollArea.setStyleSheet("border: none;")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 887, 521))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget_2.addWidget(self.page1_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.pushButton_30 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_30.setGeometry(QtCore.QRect(10, 100, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_30.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_31.setGeometry(QtCore.QRect(10, 160, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_31.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_32.setGeometry(QtCore.QRect(10, 220, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_32.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_33.setGeometry(QtCore.QRect(10, 280, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_33.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_33.setObjectName("pushButton_33")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(390, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("    color: white;")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.stackedWidget_2.addWidget(self.page_3)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pushButton_24 = QtWidgets.QPushButton(self.page)
        self.pushButton_24.setGeometry(QtCore.QRect(10, 220, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_24.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.page)
        self.pushButton_25.setGeometry(QtCore.QRect(10, 280, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_25.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.page)
        self.pushButton_26.setGeometry(QtCore.QRect(10, 100, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_26.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.page)
        self.pushButton_27.setGeometry(QtCore.QRect(10, 160, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_27.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_27.setObjectName("pushButton_27")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_4.setGeometry(QtCore.QRect(390, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("    color: white;")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.pushButton_28 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_28.setGeometry(QtCore.QRect(10, 220, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_28.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_29.setGeometry(QtCore.QRect(10, 280, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_29.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_35 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_35.setGeometry(QtCore.QRect(10, 100, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_35.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_36.setGeometry(QtCore.QRect(10, 160, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_36.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_36.setObjectName("pushButton_36")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(390, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("    color: white;")
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.stackedWidget_2.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.pushButton_37 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_37.setGeometry(QtCore.QRect(10, 280, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_37.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_38.setGeometry(QtCore.QRect(10, 100, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_38.setFont(font)
        self.pushButton_38.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_38.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_39 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_39.setGeometry(QtCore.QRect(10, 160, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_39.setFont(font)
        self.pushButton_39.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_39.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_40.setGeometry(QtCore.QRect(10, 220, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_40.setFont(font)
        self.pushButton_40.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_40.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_40.setObjectName("pushButton_40")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(390, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("    color: white;")
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.pushButton_41 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_41.setGeometry(QtCore.QRect(10, 280, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_41.setFont(font)
        self.pushButton_41.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_41.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_42 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_42.setGeometry(QtCore.QRect(10, 220, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_42.setFont(font)
        self.pushButton_42.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_42.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_43 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_43.setGeometry(QtCore.QRect(10, 100, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_43.setFont(font)
        self.pushButton_43.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_43.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_44 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_44.setGeometry(QtCore.QRect(10, 160, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_44.setFont(font)
        self.pushButton_44.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_44.setStyleSheet("QPushButton {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"\n"
"}")
        self.pushButton_44.setObjectName("pushButton_44")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_7.setGeometry(QtCore.QRect(390, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("    color: white;")
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.stackedWidget_2.addWidget(self.page_5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "Categórias"))
        self.pushButton_34.setText(_translate("MainWindow", "PushButton"))
        self.label_3.setText(_translate("MainWindow", "CAST"))
        self.pushButton.setText(_translate("MainWindow", "AÇÃO"))
        self.pushButton_5.setText(_translate("MainWindow", "COMÉDIA"))
        self.pushButton_6.setText(_translate("MainWindow", "DRAMA"))
        self.pushButton_7.setText(_translate("MainWindow", "TERROR"))
        self.pushButton_8.setText(_translate("MainWindow", "INFANTIL"))
        self.pushButton_9.setText(_translate("MainWindow", "ANIMES"))
        self.label_2.setText(_translate("MainWindow", "EXPLORE"))
        self.lineEdit.setText(_translate("MainWindow", "SELECIONE UMA CATEGÓRIA, USER!"))
        self.pushButton_30.setText(_translate("MainWindow", "FILME"))
        self.pushButton_31.setText(_translate("MainWindow", "FILME"))
        self.pushButton_32.setText(_translate("MainWindow", "FILME"))
        self.pushButton_33.setText(_translate("MainWindow", "FILME"))
        self.lineEdit_3.setText(_translate("MainWindow", "COMÉDIA"))
        self.pushButton_24.setText(_translate("MainWindow", "FILME"))
        self.pushButton_25.setText(_translate("MainWindow", "FILME"))
        self.pushButton_26.setText(_translate("MainWindow", "FILME"))
        self.pushButton_27.setText(_translate("MainWindow", "FILME"))
        self.lineEdit_4.setText(_translate("MainWindow", "DRAMA"))
        self.pushButton_28.setText(_translate("MainWindow", "FILME"))
        self.pushButton_29.setText(_translate("MainWindow", "FILME"))
        self.pushButton_35.setText(_translate("MainWindow", "FILME"))
        self.pushButton_36.setText(_translate("MainWindow", "FILME"))
        self.lineEdit_5.setText(_translate("MainWindow", "TERROR"))
        self.pushButton_37.setText(_translate("MainWindow", "FILME"))
        self.pushButton_38.setText(_translate("MainWindow", "FILME"))
        self.pushButton_39.setText(_translate("MainWindow", "FILME"))
        self.pushButton_40.setText(_translate("MainWindow", "FILME"))
        self.lineEdit_6.setText(_translate("MainWindow", "INFANTIL"))
        self.pushButton_41.setText(_translate("MainWindow", "FILME"))
        self.pushButton_42.setText(_translate("MainWindow", "FILME"))
        self.pushButton_43.setText(_translate("MainWindow", "FILME"))
        self.pushButton_44.setText(_translate("MainWindow", "FILME"))
        self.lineEdit_7.setText(_translate("MainWindow", "ANIMES"))
