# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_inicialOFC.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Inicial(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 640)
        MainWindow.setMinimumSize(QtCore.QSize(1250, 640))
        MainWindow.setMaximumSize(QtCore.QSize(1250, 640))
        MainWindow.setStyleSheet("background-color: rgb(10, 3, 34);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(-10, 0, 1251, 101))
        self.frame_4.setStyleSheet("background-color: black;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setGeometry(QtCore.QRect(130, 70, 91, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"color: white;\n"
"border: 0.5px solid white;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:black;\n"
"    background-color: white;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 70, 91, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"color: white;\n"
"border: 0.5px solid white;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:black;\n"
"    background-color: white;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setGeometry(QtCore.QRect(1220, 70, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-image: url(:/newPrefix/align-justify (3).svg);\n"
"background-repeat: no-repeat;\n"
"color: white;\n"
"border: none;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(580, 40, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: white;\n"
"border-bottom: 1px solid yellow;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 590, 1251, 51))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(490, 10, 301, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;\n"
"border-bottom: 1px solid yellow;\n"
"padding-bottom:3px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 180, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"color: white;\n"
"border: 1px solid white;\n"
"border-radius:2px;\n"
"padding: 5px;\n"
"}\n"
"\n"
"Qlabel:hover {\n"
"    color: white;\n"
"    background-color: white;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(230, 240, 161, 101))
        self.frame_3.setStyleSheet("background-color: white;\n"
"border: 1px solid yellow;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(650, 240, 161, 101))
        self.frame_6.setStyleSheet("background-color: white;\n"
"border: 1px solid yellow;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(860, 240, 161, 101))
        self.frame_7.setStyleSheet("background-color: white;\n"
"border: 1px solid yellow;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 390, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white;\n"
"border: 1px solid white;\n"
"padding: 5px;\n"
"border-radius:2px;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.frame_17 = QtWidgets.QFrame(self.centralwidget)
        self.frame_17.setGeometry(QtCore.QRect(440, 450, 161, 101))
        self.frame_17.setStyleSheet("background-color: white;\n"
"border: 1px solid yellow;")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.frame_24 = QtWidgets.QFrame(self.centralwidget)
        self.frame_24.setGeometry(QtCore.QRect(650, 450, 161, 101))
        self.frame_24.setStyleSheet("background-color: white;\n"
"border: 1px solid yellow;")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.frame_25 = QtWidgets.QFrame(self.frame_24)
        self.frame_25.setGeometry(QtCore.QRect(0, 60, 161, 101))
        self.frame_25.setStyleSheet("background-color: white;")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.frame_26 = QtWidgets.QFrame(self.frame_24)
        self.frame_26.setGeometry(QtCore.QRect(210, 60, 161, 101))
        self.frame_26.setStyleSheet("background-color: white;")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.frame_27 = QtWidgets.QFrame(self.frame_24)
        self.frame_27.setGeometry(QtCore.QRect(420, 60, 161, 101))
        self.frame_27.setStyleSheet("background-color: white;")
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.frame_28 = QtWidgets.QFrame(self.centralwidget)
        self.frame_28.setGeometry(QtCore.QRect(860, 450, 161, 101))
        self.frame_28.setStyleSheet("background-color: white;\n"
"border: 1px solid yellow;")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.frame_29 = QtWidgets.QFrame(self.frame_28)
        self.frame_29.setGeometry(QtCore.QRect(0, 60, 161, 101))
        self.frame_29.setStyleSheet("background-color: white;")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.frame_30 = QtWidgets.QFrame(self.frame_28)
        self.frame_30.setGeometry(QtCore.QRect(210, 60, 161, 101))
        self.frame_30.setStyleSheet("background-color: white;")
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.frame_31 = QtWidgets.QFrame(self.frame_28)
        self.frame_31.setGeometry(QtCore.QRect(420, 60, 161, 101))
        self.frame_31.setStyleSheet("background-color: white;")
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.frame_32 = QtWidgets.QFrame(self.centralwidget)
        self.frame_32.setGeometry(QtCore.QRect(1060, 450, 161, 101))
        self.frame_32.setStyleSheet("background-color: white;\n"
"border: 1px solid yellow;")
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.frame_34 = QtWidgets.QFrame(self.frame_32)
        self.frame_34.setGeometry(QtCore.QRect(210, 60, 161, 101))
        self.frame_34.setStyleSheet("background-color: white;")
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.frame_35 = QtWidgets.QFrame(self.frame_32)
        self.frame_35.setGeometry(QtCore.QRect(420, 60, 161, 101))
        self.frame_35.setStyleSheet("background-color: white;")
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.frame_33 = QtWidgets.QFrame(self.centralwidget)
        self.frame_33.setGeometry(QtCore.QRect(1060, 240, 161, 101))
        self.frame_33.setStyleSheet("background-color: white;\n"
"border: 1px solid yellow;")
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.frame_36 = QtWidgets.QFrame(self.frame_33)
        self.frame_36.setGeometry(QtCore.QRect(210, 60, 161, 101))
        self.frame_36.setStyleSheet("background-color: white;")
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.frame_37 = QtWidgets.QFrame(self.frame_33)
        self.frame_37.setGeometry(QtCore.QRect(420, 60, 161, 101))
        self.frame_37.setStyleSheet("background-color: white;")
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_9.setGeometry(QtCore.QRect(20, 240, 161, 101))
        self.frame_9.setStyleSheet("background-color: white;\n"
"border: 1px solid yellow;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(440, 240, 161, 101))
        self.frame_5.setStyleSheet("background-color: white;\n"
"border: 1px solid yellow;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_20 = QtWidgets.QFrame(self.centralwidget)
        self.frame_20.setGeometry(QtCore.QRect(20, 450, 161, 101))
        self.frame_20.setStyleSheet("background-color: white;\n"
"border: 1px solid yellow;")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.frame_21 = QtWidgets.QFrame(self.frame_20)
        self.frame_21.setGeometry(QtCore.QRect(210, 60, 161, 101))
        self.frame_21.setStyleSheet("background-color: white;")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.frame_22 = QtWidgets.QFrame(self.frame_20)
        self.frame_22.setGeometry(QtCore.QRect(420, 60, 161, 101))
        self.frame_22.setStyleSheet("background-color: white;")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.frame_16 = QtWidgets.QFrame(self.centralwidget)
        self.frame_16.setGeometry(QtCore.QRect(230, 450, 161, 101))
        self.frame_16.setStyleSheet("background-color: white;\n"
"border: 1px solid yellow;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.frame_18 = QtWidgets.QFrame(self.frame_16)
        self.frame_18.setGeometry(QtCore.QRect(210, 60, 161, 101))
        self.frame_18.setStyleSheet("background-color: white;")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.frame_19 = QtWidgets.QFrame(self.frame_16)
        self.frame_19.setGeometry(QtCore.QRect(420, 60, 161, 101))
        self.frame_19.setStyleSheet("background-color: white;")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.frame_9.raise_()
        self.frame_4.raise_()
        self.frame.raise_()
        self.label_3.raise_()
        self.frame_3.raise_()
        self.frame_6.raise_()
        self.frame_7.raise_()
        self.label_4.raise_()
        self.frame_17.raise_()
        self.frame_24.raise_()
        self.frame_28.raise_()
        self.frame_32.raise_()
        self.frame_33.raise_()
        self.frame_5.raise_()
        self.frame_20.raise_()
        self.frame_16.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", "Favoritos"))
        self.pushButton_4.setText(_translate("MainWindow", "Categórias"))
        self.label_5.setText(_translate("MainWindow", "CAST"))
        self.label_2.setText(_translate("MainWindow", "Desenvolvido por Alisson Rodrigo"))
        self.label_3.setText(_translate("MainWindow", "Em Alta"))
        self.label_4.setText(_translate("MainWindow", "Indicação Semanal"))

