# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Cadastro(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1114, 894)
        MainWindow.setStyleSheet("background-color:rgb(171, 177, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(350, 0, 601, 591))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0,0.3);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 81, 21))
        self.label_2.setStyleSheet("color: white;\n"
"font: 11pt \"Arial\";\n"
"border: 1px solid black;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.txt_nome = QtWidgets.QLineEdit(self.frame)
        self.txt_nome.setGeometry(QtCore.QRect(130, 50, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_nome.setFont(font)
        self.txt_nome.setStyleSheet("color: white")
        self.txt_nome.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_nome.setObjectName("txt_nome")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 81, 21))
        self.label_3.setStyleSheet("color: white;\n"
"font: 11pt \"Arial\";\n"
"border: 1px solid black;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 81, 21))
        self.label_4.setStyleSheet("color: white;\n"
"font: 11pt \"Arial\";\n"
"border: 1px solid black;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 230, 91, 21))
        self.label_5.setStyleSheet("color: white;\n"
"font: 11pt \"Arial\";\n"
"border: 1px solid black;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(20, 290, 81, 21))
        self.label_6.setStyleSheet("color: white;\n"
"font: 11pt \"Arial\";\n"
"border: 1px solid black;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(20, 350, 81, 21))
        self.label_7.setStyleSheet("color: white;\n"
"font: 11pt \"Arial\";\n"
"border: 1px solid black;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.txt_email = QtWidgets.QLineEdit(self.frame)
        self.txt_email.setGeometry(QtCore.QRect(130, 110, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_email.setFont(font)
        self.txt_email.setStyleSheet("color: white")
        self.txt_email.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_email.setObjectName("txt_email")
        self.txt_endereco = QtWidgets.QLineEdit(self.frame)
        self.txt_endereco.setGeometry(QtCore.QRect(130, 170, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_endereco.setFont(font)
        self.txt_endereco.setStyleSheet("color: white")
        self.txt_endereco.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_endereco.setObjectName("txt_endereco")
        self.txt_nascimento = QtWidgets.QLineEdit(self.frame)
        self.txt_nascimento.setGeometry(QtCore.QRect(130, 230, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_nascimento.setFont(font)
        self.txt_nascimento.setStyleSheet("color: white")
        self.txt_nascimento.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_nascimento.setObjectName("txt_nascimento")
        self.txt_usuario = QtWidgets.QLineEdit(self.frame)
        self.txt_usuario.setGeometry(QtCore.QRect(130, 290, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_usuario.setFont(font)
        self.txt_usuario.setStyleSheet("color: white")
        self.txt_usuario.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_usuario.setObjectName("txt_usuario")
        self.txt_senha = QtWidgets.QLineEdit(self.frame)
        self.txt_senha.setGeometry(QtCore.QRect(130, 350, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_senha.setFont(font)
        self.txt_senha.setStyleSheet("color: white")
        self.txt_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_senha.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_senha.setObjectName("txt_senha")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(20, 420, 141, 21))
        self.label_8.setStyleSheet("color: white;\n"
"font: 11pt \"Arial\";\n"
"border: 1px solid black;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.txt_senhaconf = QtWidgets.QLineEdit(self.frame)
        self.txt_senhaconf.setGeometry(QtCore.QRect(180, 420, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_senhaconf.setFont(font)
        self.txt_senhaconf.setStyleSheet("color: white")
        self.txt_senhaconf.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_senhaconf.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_senhaconf.setObjectName("txt_senhaconf")
        self.botao_cadastrar = QtWidgets.QPushButton(self.frame)
        self.botao_cadastrar.setGeometry(QtCore.QRect(290, 540, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.botao_cadastrar.setFont(font)
        self.botao_cadastrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_cadastrar.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border-radius :10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgray;\n"
"}\n"
"\n"
"")
        self.botao_cadastrar.setObjectName("botao_cadastrar")
        self.planos_assinatura = QtWidgets.QComboBox(self.frame)
        self.planos_assinatura.setGeometry(QtCore.QRect(180, 490, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.planos_assinatura.setFont(font)
        self.planos_assinatura.setStyleSheet("color: black;\n"
"background: white;")
        self.planos_assinatura.setEditable(False)
        self.planos_assinatura.setCurrentText("")
        self.planos_assinatura.setObjectName("planos_assinatura")
        self.planos_assinatura.addItem("")
        self.planos_assinatura.addItem("")
        self.planos_assinatura.setItemText(1, "Plano Básico (19,00)")
        self.planos_assinatura.addItem("")
        self.planos_assinatura.addItem("")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(20, 490, 141, 21))
        self.label_9.setStyleSheet("color: white;\n"
"font: 11pt \"Arial\";\n"
"border: 1px solid black;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.botao_saibamais = QtWidgets.QPushButton(self.frame)
        self.botao_saibamais.setGeometry(QtCore.QRect(510, 490, 75, 23))
        self.botao_saibamais.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_saibamais.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border-radius :10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgray;\n"
"}\n"
"\n"
"")
        self.botao_saibamais.setObjectName("botao_saibamais")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 180, 131, 151))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../imagens/cadastro.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border-radius :10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgray;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label.raise_()
        self.frame.raise_()
        self.pushButton_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Nome"))
        self.txt_nome.setPlaceholderText(_translate("MainWindow", "Digite seu nome"))
        self.label_3.setText(_translate("MainWindow", "Email"))
        self.label_4.setText(_translate("MainWindow", "Endereço"))
        self.label_5.setText(_translate("MainWindow", "Nascimento"))
        self.label_6.setText(_translate("MainWindow", "Usuário"))
        self.label_7.setText(_translate("MainWindow", "Senha"))
        self.txt_email.setPlaceholderText(_translate("MainWindow", "Digite seu email"))
        self.txt_endereco.setPlaceholderText(_translate("MainWindow", "Digite seu endereço"))
        self.txt_nascimento.setPlaceholderText(_translate("MainWindow", "Digite sua data de nascimento"))
        self.txt_usuario.setPlaceholderText(_translate("MainWindow", "Digite seu nome de usuário"))
        self.txt_senha.setPlaceholderText(_translate("MainWindow", "Digite sua senha"))
        self.label_8.setText(_translate("MainWindow", "Confirmar Senha"))
        self.txt_senhaconf.setPlaceholderText(_translate("MainWindow", "Digite sua senha novamente"))
        self.botao_cadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.planos_assinatura.setPlaceholderText(_translate("MainWindow", "Selecione um plano"))
        self.planos_assinatura.setItemText(0, _translate("MainWindow", "Selecione um Plano..."))
        self.planos_assinatura.setItemText(2, _translate("MainWindow", "Plano Normal (25,00)"))
        self.planos_assinatura.setItemText(3, _translate("MainWindow", "Plano Premium (35,00)"))
        self.label_9.setText(_translate("MainWindow", "Planos de Assinatura"))
        self.botao_saibamais.setText(_translate("MainWindow", "Saiba mais"))
        self.pushButton_2.setText(_translate("MainWindow", "Voltar"))
