# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(652, 614)
        Login.setStyleSheet("background-color:rgb(171, 177, 255);")
        self.frame = QtWidgets.QFrame(Login)
        self.frame.setGeometry(QtCore.QRect(140, 160, 411, 351))
        self.frame.setStyleSheet("background-color: rgba(0, 0, 0,0.2);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.txt_user = QtWidgets.QLineEdit(self.frame)
        self.txt_user.setGeometry(QtCore.QRect(100, 100, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_user.setFont(font)
        self.txt_user.setStyleSheet("color: white;")
        self.txt_user.setText("")
        self.txt_user.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_user.setObjectName("txt_user")
        self.txt_password = QtWidgets.QLineEdit(self.frame)
        self.txt_password.setGeometry(QtCore.QRect(100, 150, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_password.setFont(font)
        self.txt_password.setStyleSheet("color: white;")
        self.txt_password.setText("")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_password.setObjectName("txt_password")
        self.button_login = QtWidgets.QPushButton(self.frame)
        self.button_login.setGeometry(QtCore.QRect(170, 200, 75, 23))
        self.button_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_login.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border-radius :10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgray;\n"
"}")
        self.button_login.setObjectName("button_login")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(200, 230, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: none;")
        self.label_2.setObjectName("label_2")
        self.button_register = QtWidgets.QPushButton(self.frame)
        self.button_register.setGeometry(QtCore.QRect(170, 270, 75, 23))
        self.button_register.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_register.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border-radius :10px\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgray;\n"
"}")
        self.button_register.setObjectName("button_register")
        self.label = QtWidgets.QLabel(Login)
        self.label.setGeometry(QtCore.QRect(290, 60, 131, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../imagens/icon_title.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Login)
        self.pushButton.setGeometry(QtCore.QRect(10, 583, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border-radius :10px\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgray;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label.raise_()
        self.frame.raise_()
        self.pushButton.raise_()

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.txt_user.setPlaceholderText(_translate("Login", "Username"))
        self.txt_password.setPlaceholderText(_translate("Login", "Password"))
        self.button_login.setText(_translate("Login", "Login"))
        self.label_2.setText(_translate("Login", "Or"))
        self.button_register.setText(_translate("Login", "Register"))
        self.pushButton.setText(_translate("Login", "Sair"))
